site_name: condax
site_description: Install and run applications packaged with conda in isolated environments

theme:
  name: "material"
repo_name: mariusvniekerk/condax
repo_url: https://github.com/mariusvniekerk/condax

nav:
  - Home: "index.md"
  - Installation: "installation.md"
  - Commands: "commands.md"
  - Configuration: "config.md"
  - How condax works: "how-this-works.md"
  - Contributing: "contributing.md"
  - Changelog: "changelog.md"
